import MainWrapper from "@/components/MainWrapper/MainWrapper";
import VendorWrapper from "@/components/VendorComponents/VendorWrapper/VendorWrapper";
import "@/app/global.scss"

export const metadata = {
    title: "Vendor - Onetapdrive",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <MainWrapper>
                    <VendorWrapper>
                        {children}
                    </VendorWrapper>
                </MainWrapper>
            </body>
        </html>
    );
}
