import Head from "next/head";


export const metadata = {
    title: "User - Onetapdrive",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    );
}
