import '../global.scss';
import MainWrapper from "@/components/MainWrapper/MainWrapper";
import AdminWrapper from "@/components/AdminComponents/AdminWrapper/AdminWrapper";
import "./AdminGlobal.scss"

export const metadata = {
    title: "Admin - Onetapdrive",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <MainWrapper>
                    <AdminWrapper>
                        {children}
                    </AdminWrapper>
                </MainWrapper>
            </body>
        </html>
    );
}
